[SEM-008] #11 : SecondaryButton
Ditmar/backoffice-openscience pull request #108
Opened 2024-10-03 01:08 UTC by armandogear5

2024-10-03 01:38 UTC, Ditmar requested changes
estas borrando las pruebas de concepto que se hicieron ese codigo no debes eliminarlo.
![image](https://github.com/user-attachments/assets/4814e9fc-b66f-491e-aed8-105a80cbb5c2)

2024-10-03 02:36 UTC, armandogear5 commented
carpetas recuradas

2024-10-03 02:37 UTC, armandogear5 commented
las pruebas borradas de concepto que se hicieron se recuperaron

2024-10-04 03:11 UTC, Ditmar requested changes
![image](https://github.com/user-attachments/assets/2e94d60a-3d6b-4427-8fb7-8e825552b3d4)

2024-10-04 03:11 UTC, Ditmar commented on src/ui/components/demo/calculator/Calculator.tsx
please don't remove the apoc components

2024-10-04 03:42 UTC, armandogear5 commented on src/ui/components/demo/calculator/Calculator.tsx
apoc components spare parts

2024-10-06 01:20 UTC, closed without merging