feature[common]: added button yes/no
Ditmar/backoffice-openscience pull request #110
Opened 2024-10-03 02:45 UTC by Beymar-Cejas

2024-10-06 20:14 UTC, Ditmar requested changes
please rebase your pr, and check the comments

2024-10-06 20:14 UTC, Ditmar commented on src/ui/atoms/ButtonYesNo/Button.tsx
> +  const colorFont = styles[`button-label--${variant}`];
You should use another approach to set up your variants, check this example to fix your pr . https://github.com/Ditmar/backoffice-openscience/blob/master/src/ui/components/demo/calculator/atoms/display.tsx#L7-L10

2024-10-08 04:51 UTC, Beymar-Cejas commented
https://github.com/Ditmar/backoffice-openscience/tree/feature/SEM-038/src/ui/components/atoms/ButtonYesNo

2024-10-09 01:44 UTC, DanX3N0 commented
post the link of the storybook component

2024-10-10 02:30 UTC, Beymar-Cejas commented
this is storybook
https://github.com/Ditmar/backoffice-openscience/blob/455fe03a4119d585913bbcb20a27ed5aa9c415ed/src/ui/components/atoms/ButtonYesNo/Button.stories.tsx

2024-10-14 20:23 UTC, Beymar-Cejas commented
feature/SEM-038
https://ditmar.github.io/backoffice-openscience/branch-feature/SEM-038/?path=src/ui/atoms/ButtonYesNo

2024-10-15 11:38 UTC, DanX3N0 commented
remove the shadow: 
![{97CE8C94-5153-4A58-AC29-95DFF6F89F64}](https://github.com/user-attachments/assets/67ba8ae6-9000-44da-a3f8-dc408aa50d7d)

2024-10-23 00:59 UTC, Ditmar approved these changes

2024-10-23 00:59 UTC, merged