[SEM-35]: Implementation of Buttons in the Sidebar Menu for Managing Articles and Authors
Ditmar/backoffice-openscience pull request #113
Opened 2024-10-03 05:06 UTC by Then-Crimson

## [SEM-35]: Sidebar Button Implementation

### Description
Implemented "Manage Articles" and "Manage Authors" buttons in the sidebar to improve navigation.

### Acceptance Criteria
- Buttons integrated as per design.
- Icons and labels correctly aligned and sized.

### Storybook Implementation
- Entries created for Normal and Hover states.
- Controls added to test different states.

### TDD
- Unit tests for navigation and state changes.
- Coverage for color changes and alignment.

### Notes
- CSS used for styling and compatibility.

### Attachments
![image](https://github.com/user-attachments/assets/e0151aaf-fc36-4161-97ef-8f0e8305d723)
![image](https://github.com/user-attachments/assets/cf112f5c-0d10-4aa6-a9ab-623dedd2445c)

2024-10-07 00:04 UTC, Ditmar requested changes
good work, please read the comments

2024-10-07 00:04 UTC, Ditmar commented on src/ui/components/atoms/side-menu-button/SideMenuButton.tsx
> +      } ${isActive ? styles.active : ''}`}
this logic will be difficult to maintain in the future. please use this approach https://github.com/Ditmar/backoffice-openscience/blob/master/src/ui/components/demo/calculator/atoms/display.tsx#L7-L10

2024-10-15 23:38 UTC, Then-Crimson commented
https://ditmar.github.io/backoffice-openscience/branch-feature/SEM-035/?path=/story/ui-components-atoms-side-menu-button--article 
Storybook--

2024-10-23 01:25 UTC, Then-Crimson commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-035/?path=/story/ui-components-atoms-side-menu-button--article
for storybook

2024-10-28 03:36 UTC, Then-Crimson commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-035/?path=/story/ui-components-atoms-side-menu-button--article R3.0

2024-11-06 01:54 UTC, Then-Crimson commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-035/?path=/story/ui-components-atoms-side-menu-button--article
R4.0

2024-11-06 03:29 UTC, Ditmar approved these changes

2024-11-06 03:29 UTC, merged