Feature/sem 023
Ditmar/backoffice-openscience pull request #145
Opened 2024-10-09 03:47 UTC by ELVISrodrigo123

feature/SEM-023
https://ditmar.github.io/backoffice-openscience/branch-feature/SEM-023/?path=src/ui/atoms/TabLabel

2024-10-14 19:19 UTC, DanX3N0 commented
check the font

2024-10-15 16:13 UTC, Ditmar requested changes
Nice work only a few comments there

2024-10-15 16:13 UTC, Ditmar commented on src/ui/components/atoms/TabLabel/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap');
please use another approach to embed the font. Use this approach 
https://github.com/Ditmar/OpenScience/blob/main/src/globals/_fonts.scss

2024-10-16 18:32 UTC, Ditmar requested changes
lee el comentario

2024-10-16 18:32 UTC, Ditmar commented on src/globals/_fonts.scss
> +        src: url('/fonts/Lato-Regular.woff2') format('woff2');
solo copiaste el archivo del otro proyecto, esto esta mal tienes que adpatarlo al tipo de fuente que deseas importar

2024-10-27 14:08 UTC, Ditmar requested changes
Please check the rebase something is bad 
![image](https://github.com/user-attachments/assets/91b69f3d-45a9-4a2f-a72a-b919997d91f2)
you are pushing changes that are not yours

2024-10-28 03:05 UTC, Ditmar approved these changes

2024-10-28 03:05 UTC, merged