[SEM-093]: FORM FIELDS FROM SEO SETTINGS
Ditmar/backoffice-openscience pull request #165
Opened 2024-11-05 03:26 UTC by MadelenC

We need to implement a component that contains the elements shown in the image, thus containing all the form fields, as well as integrating the editing component shown in the image.

2024-11-05 03:36 UTC, MadelenC commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-093/?path=/story/components-seosettingsform--default
this is for storybook

2024-11-14 12:38 UTC, Ditmar requested changes
lea los comentarios

2024-11-14 12:38 UTC, Ditmar commented on src/components/SEOSettingsForm/SEOSettingsForm.test.tsx
> +import '@testing-library/jest-dom';
por que necesitas importar jest, estamos usando vitest

2024-11-14 12:38 UTC, Ditmar commented on src/components/SEOSettingsForm/SEOSettingsForm.tsx
> +            <input id="meta_title" type="text" placeholder="Placeholder text" />
el input deberia ser un atomo y esperar los props para sus variantes

2024-11-14 12:38 UTC, Ditmar commented on src/components/SEOSettingsForm/SEOSettingsForm.tsx
> +            <input id="og_image_height" type="text" placeholder="Placeholder text" />
el input deberia ser un atomo y esperar los props para sus variantes

2024-11-14 12:39 UTC, Ditmar commented
igual no lo veo bien en el storybook en otras resoluciones 
![image](https://github.com/user-attachments/assets/b6cad675-5f96-479d-be08-dea1e1277bcb)

2024-11-18 02:16 UTC, MadelenC commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-093/?path=/story/components-seosettingsform--default

2024-12-06 22:32 UTC, MadelenC commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-093/?path=/story/components-seosettingsform--default

2024-12-09 00:51 UTC, Ditmar approved these changes

2024-12-09 00:51 UTC, Ditmar commented on src/components/SEOSettingsForm/SEOSettingsForm.stories.tsx
> +  title: 'Components/SEOSettingsForm',
this part of code should be on like a molecules

2024-12-09 00:51 UTC, merged