SEM-95] FORM FIELDS FORM USER MANAGEMENT
Ditmar/backoffice-openscience pull request #196
Opened 2024-11-15 23:42 UTC by JorgePachecoCordova

Description
We need to implement a component that contains the elements shown in the image, thus containing all the form fields, as well as integrating the editing component shown in the image.

Acceptance Criteria
Integrate the component into the appropriate section shown in the images.
Ensure that icons and labels are aligned and sized correctly as shown in the screenshots.

Color Variants
See figure.

Implementation in Storybook:
Create entries in Storybook for each button to show the existing states of the component.
Include controls to allow testing of different states and properties.

Test Driven Development (TDD):
Write unit tests for both buttons to verify navigation and state changes.
Ensure that tests cover color changes on hover and alignment of icons and labels.
![image](https://github.com/user-attachments/assets/654d7ae4-07f7-4ee4-a02b-5b8d2a7fa470)

2024-11-22 01:35 UTC, Ditmar requested changes
good job please put the url of the storybook to check the component

2024-11-22 01:35 UTC, Ditmar commented on src/ui/components/molecules/use-form/UserForm.test.tsx
> +    // Verificar que todos los campos tienen sus placeholders
remove the comments

2024-11-22 01:35 UTC, Ditmar commented on src/ui/components/molecules/use-form/UserForm.tsx
> +        <Placeholder placeholder="Enter your role" onChange={onChange} />
Great!

2024-11-22 02:39 UTC, JorgePachecoCordova commented on src/ui/components/molecules/use-form/UserForm.tsx
> +        <Placeholder placeholder="Enter your role" onChange={onChange} />
https://ditmar.github.io/backoffice-openscience/branch-SEM-95/?path=/story/ui-components-molecules-user-form--default
story

2024-11-24 18:31 UTC, Ditmar approved these changes

2024-11-24 18:31 UTC, merged