[SEM-91] #91 : Component of volume management
Ditmar/backoffice-openscience pull request #202
Opened 2024-11-18 08:07 UTC by 11royer

We need to implement a component that contains the elements shown in the image, thus containing all the form fields, as well as integrating the editing component shown in the image.

2024-11-18 08:15 UTC, 11royer commented
This is my ticket URL:
https://ditmar.github.io/backoffice-openscience/branch-SEM-91/?path=/story/ui-components-atoms-volume-management

2024-11-22 01:28 UTC, Ditmar requested changes
read the comments

2024-11-22 01:28 UTC, Ditmar commented on src/ui/components/atoms/volume-management/VolumeManagement.tsx
> +import classNames from 'classnames';
this component don't should be a atom, this component must be an organism

2024-11-22 01:28 UTC, Ditmar commented on src/ui/components/atoms/volume-management/VolumeManagement.tsx
> +          <span>Click to add an asset or drag and drop one in this area</span>
this should be a separate component, only for managing images, and it is necessary to add the drag events to added files there, this component should be a molecule,

2024-12-06 18:52 UTC, closed without merging