feature/SEM-61
Ditmar/backoffice-openscience pull request #213
Opened 2024-11-22 14:27 UTC by ELVISrodrigo123

feature/SEM-61
https://ditmar.github.io/backoffice-openscience/branch-SEM-61/?path=/story/ui-components-atoms-checklist--default
https://github.com/Ditmar/backoffice-openscience/issues/61

2024-11-23 03:05 UTC, DanX3N0 commented
not according to figma: 

![{962EDB45-E8B0-459E-ADDB-E0A1AEF39B5E}](https://github.com/user-attachments/assets/c47046fd-1551-4696-8d99-31c4c9d6f5b4)

figma:

![{6342B50E-E1AA-4FB8-A54E-D9D5DDFE6C1A}](https://github.com/user-attachments/assets/43b86855-387f-4b02-9bb8-088e0c5d50f6)

check the font family

rename this: 
![{2E9E0696-672F-46F0-8085-F64FFABE2838}](https://github.com/user-attachments/assets/615562c9-aff2-423f-ba4b-9af67a7e2b1b)

the rest it's fine

2024-11-24 02:29 UTC, Ditmar requested changes
please review the figma

2024-11-27 12:51 UTC, Ditmar requested changes
please review the overlapping of the chevron with the textfiled

2024-11-27 13:14 UTC, Ditmar approved these changes

2024-11-27 13:14 UTC, merged