feature:sem-073
Ditmar/backoffice-openscience pull request #229
Opened 2024-11-26 03:38 UTC by davidcmbot11

Description
We need to implement a component that contains the elements shown in the image, thus containing all the form field
#73

2024-11-26 03:43 UTC, davidcmbot11 commented
this is my storybook 
https://ditmar.github.io/backoffice-openscience/branch-sem-073/?path=/story/ui-components-molecules-bibliographyform--basic

2024-11-26 22:09 UTC, Ditmar requested changes
Don´t use a for to create the fields,  this form is unique only create the HTML completely and check the way to catch all data, for after fetching data

2024-11-26 22:09 UTC, Ditmar commented on src/ui/components/molecules/BibliographyForm/bibliograpyform.tsx
> +      {fields.map((field) => (
i am not sure about this approach, please change this form is unique

2024-11-27 06:20 UTC, davidcmbot11 commented
new link 
https://ditmar.github.io/backoffice-openscience/branch-sem-073/?path=/story/ui-components-molecules-bibliographyform--bibliography

2024-11-27 12:52 UTC, Ditmar approved these changes

2024-11-27 12:52 UTC, merged