feature/SEM-72
Ditmar/backoffice-openscience pull request #232
Opened 2024-11-27 03:09 UTC by Beymar-Cejas

2024-11-27 03:11 UTC, Beymar-Cejas commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-72/?path=/story/molecules-topelements--primary

2024-11-27 13:04 UTC, Ditmar requested changes
please review thi figma, feel free to modify anything if you needed int he atoms component

2024-12-04 22:45 UTC, Ditmar requested changes
read the comments

2024-12-04 22:45 UTC, Ditmar commented on src/ui/components/atoms/DangerButton/Danger-Button.module.scss
> +    height: 38px;
use rem instead of px

2024-12-04 22:45 UTC, Ditmar commented on src/ui/components/atoms/DangerButton/Danger-Button.module.scss
> +    padding-inline: 20px;
use rem instead of px

2024-12-04 22:45 UTC, Ditmar commented on src/ui/components/molecules/TopElements/TopElements.module.scss
> +    @include respond-to(sm) {
use the standard sizes config in the global vars

2024-12-06 20:36 UTC, Ditmar approved these changes

2024-12-06 20:36 UTC, merged