feature/sem-022
Ditmar/backoffice-openscience pull request #237
Opened 2024-11-29 05:34 UTC by davidcmbot11

Descripción:
Como desarrollador, necesito crear y probar un componente de Links siguiendo los principios de diseño atómico. El componente debe ser inicialmente presentado en Storybook con todas sus variantes y probado usando Vitest para asegurar su funcionalidad.
Deberá de cubrir las variantes mostradas en la imagen.
#25

2024-11-29 05:37 UTC, davidcmbot11 commented
review needed, link 
https://ditmar.github.io/backoffice-openscience/branch-sem-022/?path=/story/ui-components-atoms-links--enabled

2024-12-04 23:04 UTC, Ditmar requested changes
read the comments

2024-12-04 23:04 UTC, Ditmar commented on src/ui/components/atoms/Links/links.module.scss
> +    font-family: barlow, sans-serif;
review the font

2024-12-04 23:04 UTC, Ditmar commented on src/ui/components/atoms/Links/links.module.scss
> +        text-underline-offset: 4px;
change this px to rem

2024-12-09 00:36 UTC, Ditmar approved these changes

2024-12-09 00:37 UTC, merged