feature/SEM-58
Ditmar/backoffice-openscience pull request #240
Opened 2024-11-29 19:20 UTC by giovannicv

new components

2024-11-30 19:10 UTC, giovannicv commented
i need review the PR:
https://ditmar.github.io/backoffice-openscience/branch-SEM-58/?path=/story/ui-components-atoms-side-menu-button-site-seo--site

2024-12-04 23:02 UTC, Ditmar requested changes
read the comments

2024-12-04 23:02 UTC, Ditmar commented on src/ui/components/atoms/side-menu-button-site-seo/SideMenuButtonSiteSeo.tsx
> +      window.location.href = path;
remove this line of code it is not necessary, and pass the hadleClick from props

2024-12-06 19:57 UTC, Ditmar approved these changes

2024-12-06 19:57 UTC, merged