feature/SEM-69 Bibliographies Top Elements
Ditmar/backoffice-openscience pull request #242
Opened 2024-11-30 12:11 UTC by VictoriaCk55

![image](https://github.com/user-attachments/assets/21c04817-95c1-4d50-a80b-27f6de91e494)

2024-11-30 12:45 UTC, VictoriaCk55 commented
https://ditmar.github.io/backoffice-openscience/branch-SEM-69/?path=/story/molecules-bibliographyelements--default

2024-12-04 22:31 UTC, Ditmar requested changes
read the comments

2024-12-04 22:31 UTC, Ditmar commented on src/ui/components/molecules/BibliographyElements/BibliographyElements.module.scss
> +        border: none !important;
please remove the use of the !important

2024-12-04 22:31 UTC, Ditmar commented on src/ui/components/molecules/BibliographyElements/BibliographyElements.tsx
> +            console.log('clicked');
remove the console log

2024-12-06 20:38 UTC, Ditmar approved these changes

2024-12-06 20:38 UTC, merged