[SEM-007] #10 : Secondary Button Icon +
Ditmar/backoffice-openscience pull request #76
Opened 2024-09-24 16:40 UTC by 11royer

Como desarrollador, necesito crear y probar un componente de icono +. A partir del Icono (+) de primary button agregue las variaciones de color.

2024-10-06 06:03 UTC, Ditmar requested changes
The rebase was not done correctly.

2024-10-07 08:50 UTC, 11royer commented on package-lock.json
now fixed

2024-10-07 08:58 UTC, 11royer commented on package.json
> +    "@testing-library/user-event": "^14.5.2",
The purpose of the library is to simulate hover and focus on the button, which allows interaction with the mouse:
await userEvent.hover(button);
await userEvent.unhover(button);

As well as interaction on focus:
await userEvent.tab();

2024-10-09 01:08 UTC, 11royer commented
https://github.com/Ditmar/backoffice-openscience/pull/76

2024-10-09 01:59 UTC, 11royer commented
https://ditmar.github.io/backoffice-openscience/branch-feature/SEM-007/?path=src/ui/components/atoms/secondary-button-icon

2024-10-23 02:25 UTC, closed without merging